GinnyBuddyApp/Controllers/CreateRequestController.cs
using AAH.Common;
using AAH.Common.Paging;
using AAH.Services.Contract;
using GinnyBuddyApp.Infrastructure;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AAH.Entities.V1;
using System.IO;
using System.Data;

namespace GinnyBuddyApp.Controllers
{
    public class CreateRequestController : BaseController
    {
        public readonly AbstractAddressMasterServices abstractAddressMasterServices;
        public readonly AbstractMasterPayTypeServices abstractMasterPayTypeServices;
        public readonly AbstractRequestsServices abstractRequestsServices;
        public readonly AbstractRequestDocumentsServices abstractRequestDocumentsServices;
        public readonly AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices;
        public readonly string ConnStr = "Data Source=rushkar-db-zau.cwfpajxcr0v7.ap-south-1.rds.amazonaws.com;Initial Catalog=AAH;Persist Security Info=True;User ID=sa;Password=*zZ123123;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True";
        public readonly AbstractUsersFeedbackServices abstractUsersFeedbackServices;

        public CreateRequestController(AbstractAddressMasterServices abstractAddressMasterServices,
            AbstractMasterPayTypeServices abstractMasterPayTypeServices,
            AbstractRequestsServices abstractRequestsServices,
            AbstractRequestDocumentsServices abstractRequestDocumentsServices,
            AbstractUsersFeedbackServices abstractUsersFeedbackServices,
            AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices)
        {
            this.abstractAddressMasterServices = abstractAddressMasterServices;
            this.abstractMasterPayTypeServices = abstractMasterPayTypeServices;
            this.abstractRequestsServices = abstractRequestsServices;
            this.abstractRequestDocumentsServices = abstractRequestDocumentsServices;
            this.abstractDeliveryExecutiveServices = abstractDeliveryExecutiveServices;
            this.abstractUsersFeedbackServices = abstractUsersFeedbackServices;
        }

        public ActionResult Index(string service = "", long ritype = 0)
        {
            ViewBag.SelectedService = Convert.ToString(ConvertTo.Base64Decode(service));
            ViewBag.ServiceType = ritype;
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.MasterPayTypeData = abstractMasterPayTypeServices.MasterPayType_All(pageParam, "");


            var response = abstractAddressMasterServices.SelectedAddress_ByUserId(pageParam, "", ProjectSession.AdminId);

            if (response.TotalRecords > 0)
            {
                ViewBag.DCount = abstractDeliveryExecutiveServices.GetDeliveryExecutiveCountByAddressId(response.Values[0].AddressId.ToString());
            }
            else
            {
                ViewBag.DCount = null;
            }

            return View();
        }

        public ActionResult ManageRequest()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.RequestsDataOld = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 0,0,0,2);
            ViewBag.RequestsDataToday = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 0,0,0,1);

            return View();
        }

        public ActionResult RequestDetails(long ri = 0)
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.RequestsIdData = abstractRequestsServices.Requests_ById(ri);
            ViewBag.RequestsIdDocument = abstractRequestDocumentsServices.RequestDocuments_ByRequestId(pageParam, ri);
            return View();
        }

        [HttpPost]
        public JsonResult updateConfirmRequestes(long Id = 0, long deId = 0)
        {
            try
            {
                var result = abstractRequestsServices.Request_UpdateStatus(Id, 14, deId, 0, 0, 0);
                //PushNotification.Main();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public JsonResult Update_TipAmount(long Id = 0, bool IsGiveTip = true, decimal TipAmount = 0)
        {
            try
            {
                var result = abstractRequestsServices.Update_TipAmount(Id, IsGiveTip, TipAmount);
                //PushNotification.Main();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public JsonResult cancleNewrequestes(int reId = 0, int DId = 0)
        {
            try
            {
                var result = abstractRequestsServices.Request_UpdateStatus(reId, 5, DId, 0, 0, 0);
                //PushNotification.Main();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Feedback(long rId = 0)
        {
            ViewBag.RequestId = rId;
            return View();
        }

        [HttpPost]
        public JsonResult CreateFeedbackData(string description = "", int rating = 0, long requestId = 0)
        {
            UsersFeedback abstractUsersFeedbackModel = new UsersFeedback();
            abstractUsersFeedbackModel.UserId = ProjectSession.AdminId;
            abstractUsersFeedbackModel.Description = description;
            abstractUsersFeedbackModel.RequestId = requestId;
            abstractUsersFeedbackModel.Rettings = rating;

            var result = abstractUsersFeedbackServices.UsersFeedback_Insert(abstractUsersFeedbackModel);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDataAddress()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ChooseAddressAdd(long AddressId = 0)
        {
            var result = abstractAddressMasterServices.AddressDefaultById(Convert.ToInt32(ProjectSession.AdminId), ConvertTo.Integer(AddressId));

            //SelectedAddress selectedAddress = new SelectedAddress();
            //selectedAddress.AddressId = AddressId;
            //selectedAddress.UserId = ProjectSession.AdminId;

            //var result = abstractAddressMasterServices.SelectedAddress_Insert(selectedAddress);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ChooseAddressData(long AddressId = 0)
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId);
            var j = AddressId;
            if (result.Values.Count > 0)
            {
                var ss = result.Values.Where(x => x.IsDefault == 1).ToList();
                result.Values = ss;
            }

            //var result = abstractAddressMasterServices.SelectedAddress_ByUserId(pageParam, "", ProjectSession.AdminId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CreateRequestData(HttpPostedFileBase Files, string UserDescription = "", long ServiceMasterId = 0, long PayType = 0)
        {

            Requests requests = new Requests();
            requests.UserId = ProjectSession.AdminId;
            requests.AmountRequested = 0;
            requests.UserDescription = UserDescription;
            requests.ServiceMasterId = ServiceMasterId;
            requests.PayType = PayType;
            //----------------------------------------
            //PageParam pageParam = new PageParam();
            //pageParam.Offset = 0;
            //pageParam.Limit = 1000;
            //var response = abstractAddressMasterServices.SelectedAddress_ByUserId(pageParam, "", ProjectSession.AdminId);
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var response = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId);
            if (response.Values.Count > 0)
            {
                var ss = response.Values.Where(x => x.IsDefault == 1).ToList();
                response.Values = ss;
            }
            //----------------------------------------
            if (response != null)
            {
                requests.AddressId = response.Values[0].Id;
                var result = abstractRequestsServices.Requests_Insert(requests);


                //if(Files != null)
                //{
                //    string basePath = "Re/";
                //    string fileName = DateTime.Now.ToString("ddMMyyyyhhmmss") + "_" + Path.GetFileName(Files.FileName);
                //    string path = Server.MapPath("~/" + basePath);
                //    if (!Directory.Exists(Path.Combine(HttpContext.Server.MapPath("~/" + basePath))))
                //    {
                //        Directory.CreateDirectory(HttpContext.Server.MapPath("~/" + basePath));
                //    }
                //    Files.SaveAs(HttpContext.Server.MapPath("~/" + basePath + fileName));
                //    requests.AudioUrl = basePath + fileName;

GinnyBuddyApp/Controllers/DashboardController.cs
using AAH.Common;
using AAH.Common.Paging;
using AAH.Services.Contract;
using GinnyBuddyApp.Infrastructure;
using System.Linq;
using System.Web.Mvc;

namespace GinnyBuddyApp.Controllers
{
    public class DashboardController : BaseController
    {
        public readonly AbstractOtherServiceIconsServices abstractOtherServiceIconsServices;
        public readonly AbstractRequestsServices abstractRequestsServices;
        public readonly AbstractAddressMasterServices abstractAddressMasterServices;
        public readonly AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices;
        public readonly AbstractMasterServicesServices abstractMasterServicesServices;
        public DashboardController(AbstractOtherServiceIconsServices abstractOtherServiceIconsServices,
            AbstractAddressMasterServices abstractAddressMasterServices,
             AbstractRequestsServices abstractRequestsServices,
             AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices,
             AbstractMasterServicesServices abstractMasterServicesServices)
        {
            this.abstractAddressMasterServices = abstractAddressMasterServices;
            this.abstractOtherServiceIconsServices = abstractOtherServiceIconsServices;
            this.abstractRequestsServices = abstractRequestsServices;
            this.abstractDeliveryExecutiveServices = abstractDeliveryExecutiveServices;
            this.abstractMasterServicesServices = abstractMasterServicesServices;
        }

        public ActionResult Index()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.RequestsData = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 20);
            ViewBag.MasterServicesData = abstractMasterServicesServices.MasterServices_All(pageParam, "");
            getDECountByAddress();
            return View();
        }
        [HttpPost]
        public JsonResult getDECountByAddress()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId).Values;
            if (result.Count > 0)
            {
                var ss = result.Where(x => x.IsDefault == 1).ToList();
                ViewBag.DCount = abstractDeliveryExecutiveServices.GetDeliveryExecutiveCountByAddressId(ss[0].Id.ToString());
            }
            else
            {
                ViewBag.DCount = null;
            }

            return Json(ViewBag.DCount, JsonRequestBehavior.AllowGet);
        }

        public JsonResult OtherServiceIconsData()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractOtherServiceIconsServices.OtherServiceIcons_All(pageParam,"");
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeliveryExecutiveServices()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 20);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

GinnyBuddyApp/Controllers/ProfilesController.cs
using AAH.Common;
using AAH.Common.Paging;
using AAH.Entities.Contract;
using AAH.Services.Contract;
using GinnyBuddyApp.Infrastructure;
using System;
using System.Web.Mvc;
using GinnyBuddyApp.Pages;
using AAH.Entities.V1;
using static GinnyBuddyApp.Infrastructure.Enums;

namespace GinnyBuddyApp.Controllers
{
    public class ProfilesController : BaseController
    {
        public readonly AbstractAddressMasterServices abstractAddressMasterServices;
        public readonly AbstractRequestsServices abstractRequestsServices;
        public readonly AbstractUsersServices abstractUsersServices;
        public readonly AbstractUsersFeedbackServices abstractUsersFeedbackServices;
        int redirectId = 0;
        public ProfilesController(AbstractAddressMasterServices abstractAddressMasterServices,
            AbstractRequestsServices abstractRequestsServices,
            AbstractUsersFeedbackServices abstractUsersFeedbackServices,
            AbstractUsersServices abstractUsersServices)
        {
            this.abstractAddressMasterServices = abstractAddressMasterServices;
            this.abstractRequestsServices = abstractRequestsServices;
            this.abstractUsersFeedbackServices = abstractUsersFeedbackServices;
            this.abstractUsersServices = abstractUsersServices;
        }

        public ActionResult Index()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.AddressTypeData = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId);
            ViewBag.RequestsData = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 0);
            ViewBag.FeedbackData = abstractUsersFeedbackServices.UsersFeedback_All(pageParam, "", "", "", ProjectSession.AdminId);
            ViewBag.UserData = abstractUsersServices.Users_ById(ProjectSession.AdminId).Item;
            return View();
        }

        public ActionResult EditProfile()
        {
            AbstractUsers abstractUsers = null;
            abstractUsers = abstractUsersServices.Users_ById(ProjectSession.AdminId).Item;
            ViewBag.Name = abstractUsers.FirstName;
            return View(abstractUsers);
        }

        //Create Admin Data
        [HttpPost]
        [ValidateInput(true)]
        [ActionName(Actions.UserDetailsEdit)]
        public ActionResult UserDetailsEdit(Users users)
        {
            try
            {
                AbstractUsers abstractUsers = null;
                abstractUsers = abstractUsersServices.Users_ById(ProjectSession.AdminId).Item;
                users.UpdatedBy = ProjectSession.AdminId;
                SuccessResult<AbstractUsers> result = new SuccessResult<AbstractUsers>();
                result = abstractUsersServices.Users_Upsert(users);
                if (result.Code == 200)
                {
                    if (abstractUsers.FirstName == null || abstractUsers.FirstName == "")
                    {
                        redirectId = 1;
                    }
                    else
                    {
                        redirectId = 2;
                    }

                    if (redirectId == 1)
                    {
                        return RedirectToAction(Actions.Index, Pages.Controllers.Dashboard, new { Area = "" });
                    }
                    else
                    {
                        return RedirectToAction(Actions.Index, Pages.Controllers.Profiles, new { Area = "" });
                    }
                }
                else
                {
                    TempData["openPopup"] = CommonHelper.ShowAlertMessageToastr(MessageType.danger.ToString(), result.Message);
                }
            }
            catch (Exception error)
            {
                TempData["openPopup"] = CommonHelper.ShowAlertMessageToastr(MessageType.danger.ToString(), error);
            }

            return RedirectToAction(Actions.EditProfile, Pages.Controllers.Profiles);
        }
    }
}

GinnyBuddyApp/Views/CreateRequest/ManageRequest.cshtml
@using AAH.Common;
@using GinnyBuddyApp.Pages;
@using System.Web.Optimization;
@using GinnyBuddyApp.Infrastructure;

@Html.AntiForgeryToken()

@{
    ViewBag.Title = "Manage Request";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .nav-tabs-custom .nav-item .nav-link::after{
        height:2px !important;
    }
    .nav-tabs-custom {
        border-bottom: 1px solid #dddcdc;
    }
</style>
<header id="page-topbar">
    <div class="navbar-header app-header-area p-0">
        <div class="row m-0">
            <div class="col-lg-12 col-12">
                <a href="@Url.Action("Index","Dashboard")" class="d-flex align-items-center">
                    <div id="RequestsBack" class="line-height-0">
                        <i class="dripicons-arrow-thin-left d-flex fs-20 text-dark" style="margin-right: 7px;"></i>
                    </div>
                    <h5 class="mb-0 ml-2 header-title d-flex align-items-center">My Requests</h5>
                </a>
                @*<div id="information"></div>*@
            </div>
        </div>
    </div>
</header>
<div class="main-content app-main-area mb-5">
    <div class="Address-list p-3 pt-0">
        <div class="row m-0">
            <div class="col-lg-12 col-12 p-0">
                <ul class="nav nav-tabs nav-tabs-custom nav-justified mb-2" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" style="background: transparent;" data-bs-toggle="tab" href="#TodayRequest" role="tab" aria-selected="true">
                            <span style="font-weight:600;">Today</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="background: transparent;" data-bs-toggle="tab" href="#OldRequest" role="tab" aria-selected="false">
                            <span style="font-weight:600;">Old</span>
                        </a>
                    </li>
                </ul>

                <div class="tab-content text-muted">
                    <div class="tab-pane active" id="TodayRequest" role="tabpanel">
                        @if (ViewBag.RequestsDataToday.TotalRecords > 0)
                        {
                            for (int i = 0; i < ViewBag.RequestsDataToday.TotalRecords; i++)
                            {
                                <a href="@Url.Action("RequestDetails","CreateRequest")?ri=@ViewBag.RequestsDataToday.Values[i].Id">
                                    <div class="card request-card p-2 mb-2 bg-white is-loading" style="border-radius:10px; box-shadow: 0px 0px 14px 0px #00000024; ">
                                        <div class="generate-new d-block">
                                            <div style="float:left">
                                                <span class="badge bg-soft-success text-success">@ViewBag.RequestsDataToday.Values[i].StatusName</span>
                                            </div>
                                            @if (@ViewBag.RequestsDataToday.Values[i].OTP != null && @ViewBag.RequestsDataToday.Values[i].OTP > 0 && @ViewBag.RequestsDataToday.Values[i].StatusId != 4)
                                            {
                                                <span style="float:right" class="badge bg-soft-warning text-black">@ViewBag.RequestsDataToday.Values[i].OTP</span><span style="float:right">OTP :</span>
                                            }
                                        </div>
                                        <div class="generate-details row m-0 mt-3">
                                            <div class="col-lg-6 col-6 p-0">
                                                <p class="mb-0" style="">Request Id</p>
                                                <span href="#">@ViewBag.RequestsDataToday.Values[i].Id</span>
                                            </div>
                                            <div class="col-lg-6 col-6 p-0">
                                                <p class="mb-0" style="">Raised On</p>
                                                <span href="#">@ViewBag.RequestsDataToday.Values[i].CreatedDateStr</span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            }
                        }
                        else
                        {
                            <div class="card request-card p-3 text-center mb-1" style="box-shadow: 0px 0px 6px 0px #00000024;">
                                <h5 class="mb-0">No record found</h5>
                            </div>
                        }
                    </div>
                    <div class="tab-pane" id="OldRequest" role="tabpanel">
                        @if (ViewBag.RequestsDataOld.TotalRecords > 0)
                        {
                            for (int i = 0; i < ViewBag.RequestsDataOld.TotalRecords; i++)
                            {
                                <a href="@Url.Action("RequestDetails","CreateRequest")?ri=@ViewBag.RequestsDataOld.Values[i].Id">
                                    <div class="card request-card p-2 mb-2 bg-white is-loading" style="border-radius:10px; box-shadow: 0px 0px 14px 0px #00000024; ">
                                        <div class="generate-new d-block">
                                            <div style="float:left">
                                                <span class="badge bg-soft-success text-success">@ViewBag.RequestsDataOld.Values[i].StatusName</span>
                                            </div>
                                            @if (@ViewBag.RequestsDataOld.Values[i].OTP != null && @ViewBag.RequestsDataOld.Values[i].OTP > 0 && @ViewBag.RequestsDataOld.Values[i].StatusId != 4)
                                            {
                                                <span style="float:right" class="badge bg-soft-warning text-black">@ViewBag.RequestsDataOld.Values[i].OTP</span><span style="float:right">OTP :</span>
                                            }
                                        </div>
                                        <div class="generate-details row m-0 mt-3">
                                            <div class="col-lg-6 col-6 p-0">
                                                <p class="mb-0" style="">Request Id</p>
                                                <span href="#">@ViewBag.RequestsDataOld.Values[i].Id</span>
                                            </div>
                                            <div class="col-lg-6 col-6 p-0">
                                                <p class="mb-0" style="">Raised On</p>
                                                <span href="#">@ViewBag.RequestsDataOld.Values[i].CreatedDateStr</span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            }
                        }
                        else
                        {
                            <div class="card request-card p-3 text-center mb-1" style="box-shadow: 0px 0px 6px 0px #00000024;">
                                <h5 class="mb-0">No record found</h5>
                            </div>
                        }
                    </div>
                </div>
                
            </div>
        </div>
    </div>

    @*Bottom Bar Render*@
    @RenderPage("~/Views/BottomBar/Index.cshtml")

</div>

<script src="~/assets/libs/jquery/jquery.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>

GinnyBuddyApp/Views/CreateRequest/Success.cshtml
@using AAH.Common;
@using GinnyBuddyApp.Pages;
@using System.Web.Optimization;
@using GinnyBuddyApp.Infrastructure;

@Html.AntiForgeryToken()

@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-content app-main-area">
    <div class="request-for p-3" style="display: flex; align-items: center; min-width: 100%; min-height: 75vh; justify-content: center; margin: 0 auto;">
        <img src="~/assets/images/ginny_success_gif.gif" style="width:100%" alt="Alternate Text" />
    </div>
</div>

<script src="~/assets/libs/jquery/jquery.min.js"></script>
<script>
    $(document).ready(function () {
         setTimeout(function () {
             window.location.href = "@Url.Action("Index", "Dashboard")";
         }, 3000);
    })
</script>