GinnyBuddyApp/Controllers/CreateAddressController.cs
using AAH.Common;
using AAH.Common.Paging;
using AAH.Services.Contract;
using GinnyBuddyApp.Infrastructure;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AAH.Entities.V1;
using Newtonsoft.Json;

namespace GinnyBuddyApp.Controllers
{
    public class CreateAddressController : BaseController
    {
        public readonly AbstractAddressMasterServices abstractAddressMasterServices;
        public readonly AbstractAddressTypeServices abstractAddressTypeServices;
        private readonly AbstractAreaMasterServices abstractAreaMasterServices;
        public CreateAddressController(AbstractAddressMasterServices abstractAddressMasterServices,
            AbstractAddressTypeServices abstractAddressTypeServices, AbstractAreaMasterServices abstractAreaMasterServices)
        {
            this.abstractAddressMasterServices = abstractAddressMasterServices;
            this.abstractAddressTypeServices = abstractAddressTypeServices;
            this.abstractAreaMasterServices = abstractAreaMasterServices;
        }


        public ActionResult Index(int ri = 0)
        {
            ViewBag.ri = ri;
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.AdressTypeData = abstractAddressTypeServices.AddressType_All(pageParam, "");
            return View();
        }

        [HttpPost]
        public JsonResult ManageAddressId(int Id = 0)
        {
            //var result = abstractAddressMasterServices.AddressDefaultById(Convert.ToInt32(ProjectSession.AdminId), Id);
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractAddressMasterServices.AddressMaster_ById(Id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ManageAddress()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.AddressTypeData = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId);
            return View();
        }

        [HttpPost]
        public JsonResult CreateAddressMy(AddressMasterRequestModel addressMaster)
        {

            addressMaster.UserId = ProjectSession.AdminId;

            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 10000;
            var areaData = abstractAreaMasterServices.AreaMaster_All(pageParam, "").Values;
            var isInArea = false;
            for (int i = 0; i < areaData.Count; i++)
            {
                if (areaData[i].IsActive)
                {
                    List<double> latlong = new List<double>();
                    double l = new double();
                    l = Convert.ToDouble(addressMaster.Latitude);
                    latlong.Add(l);
                    l = Convert.ToDouble(addressMaster.Longitute);
                    latlong.Add(l);

                    if (areaData[i].GeoFencing != null)
                    {
                        var polygonData = JsonConvert.DeserializeObject<List<ARoot>>(areaData[i].GeoFencing);
                        isInArea = inside(polygonData, latlong);

                        if (isInArea)
                        {
                            addressMaster.AreaMasterId = areaData[i].Id;
                        }
                    }
                }
            }

            var result = abstractAddressMasterServices.AddressMaster_Upsert(addressMaster);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeletedAddressData(long AddressId = 0)
        {
            var result = abstractAddressMasterServices.AddressMaster_Delete(AddressId, ProjectSession.AdminId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public bool inside(List<ARoot> vs, List<double> point)
        {

            var x = point[0];
            var y = point[1];

            var inside = false;
            for (int i = 0, j = vs.Count - 1; i < vs.Count; j = i++)
            {
                var xi = vs[i].lat;
                var yi = vs[i].lng;
                var xj = vs[j].lat;
                var yj = vs[j].lng;

                var intersect = ((yi > y) != (yj > y))
                    && (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
                if (intersect) inside = !inside;
            }

            return inside;
        }

        //public bool inside(pRoot vs, List<double> point)
        //{

        //    var x = point[0];
        //    var y = point[1];

        //    var inside = false;
        //    for (int i = 0, j = vs.MyArray.Count - 1; i < vs.MyArray.Count; j = i++)
        //    {
        //        var xi = vs.MyArray[i][0];
        //        var yi = vs.MyArray[i][1];
        //        var xj = vs.MyArray[j][0];
        //        var yj = vs.MyArray[j][1];

        //        var intersect = ((yi > y) != (yj > y))
        //            && (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
        //        if (intersect) inside = !inside;
        //    }

        //    return inside;
        //}
        public class pRoot
        {
            public List<List<double>> MyArray { get; set; }
        }

        public class ARoot
        {
            public double lat { get; set; }
            public double lng { get; set; }
        }
    }
}

GinnyBuddyApp/Controllers/ProfilesController.cs
using AAH.Common;
using AAH.Common.Paging;
using AAH.Entities.Contract;
using AAH.Services.Contract;
using GinnyBuddyApp.Infrastructure;
using System;
using System.Web.Mvc;
using GinnyBuddyApp.Pages;
using AAH.Entities.V1;
using static GinnyBuddyApp.Infrastructure.Enums;

namespace GinnyBuddyApp.Controllers
{
    public class ProfilesController : BaseController
    {
        public readonly AbstractAddressMasterServices abstractAddressMasterServices;
        public readonly AbstractRequestsServices abstractRequestsServices;
        public readonly AbstractUsersServices abstractUsersServices;
        public readonly AbstractUsersFeedbackServices abstractUsersFeedbackServices;
        int redirectId = 0;
        public ProfilesController(AbstractAddressMasterServices abstractAddressMasterServices,
            AbstractRequestsServices abstractRequestsServices,
            AbstractUsersFeedbackServices abstractUsersFeedbackServices,
            AbstractUsersServices abstractUsersServices)
        {
            this.abstractAddressMasterServices = abstractAddressMasterServices;
            this.abstractRequestsServices = abstractRequestsServices;
            this.abstractUsersFeedbackServices = abstractUsersFeedbackServices;
            this.abstractUsersServices = abstractUsersServices;
        }

        public ActionResult Index()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.AddressTypeData = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId);
            ViewBag.RequestsData = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 0);
            ViewBag.FeedbackData = abstractUsersFeedbackServices.UsersFeedback_All(pageParam, "", "", "", ProjectSession.AdminId);
            ViewBag.UserData = abstractUsersServices.Users_ById(ProjectSession.AdminId).Item;
            return View();
        }

        public ActionResult EditProfile()
        {
            AbstractUsers abstractUsers = null;
            abstractUsers = abstractUsersServices.Users_ById(ProjectSession.AdminId).Item;
            ViewBag.Name = abstractUsers.FirstName;
            return View(abstractUsers);
        }

        //Create Admin Data
        [HttpPost]
        [ValidateInput(true)]
        [ActionName(Actions.UserDetailsEdit)]
        public ActionResult UserDetailsEdit(Users users)
        {
            try
            {
                AbstractUsers abstractUsers = null;
                abstractUsers = abstractUsersServices.Users_ById(ProjectSession.AdminId).Item;
                users.UpdatedBy = ProjectSession.AdminId;
                SuccessResult<AbstractUsers> result = new SuccessResult<AbstractUsers>();
                result = abstractUsersServices.Users_Upsert(users);
                if (result.Code == 200)
                {
                    if (abstractUsers.FirstName == null || abstractUsers.FirstName == "")
                    {
                        redirectId = 1;
                    }
                    else
                    {
                        redirectId = 2;
                    }

                    if (redirectId == 1)
                    {
                        return RedirectToAction(Actions.Index, Pages.Controllers.Dashboard, new { Area = "" });
                    }
                    else
                    {
                        return RedirectToAction(Actions.Index, Pages.Controllers.Profiles, new { Area = "" });
                    }
                }
                else
                {
                    TempData["openPopup"] = CommonHelper.ShowAlertMessageToastr(MessageType.danger.ToString(), result.Message);
                }
            }
            catch (Exception error)
            {
                TempData["openPopup"] = CommonHelper.ShowAlertMessageToastr(MessageType.danger.ToString(), error);
            }

            return RedirectToAction(Actions.EditProfile, Pages.Controllers.Profiles);
        }
    }
}

GinnyBuddyApp/Views/CreateAddress/ManageAddress.cshtml
@using AAH.Common;
@using GinnyBuddyApp.Pages;
@using System.Web.Optimization;
@using GinnyBuddyApp.Infrastructure;

@Html.AntiForgeryToken()

@{
    ViewBag.Title = "Manage Address";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #map-canvas {
        height: 180px;
        width: 100%;
    }
</style>
<header id="page-topbar">
    <div class="navbar-header app-header-area p-0">
        <div class="row m-0">
            <div class="col-lg-12 col-12">
                <a href="@Url.Action("Index","Profiles")" class="d-flex align-items-center">
                    <div id="AddressBack" class="line-height-0">
                        <i class="dripicons-arrow-thin-left d-flex fs-20 text-dark" style="margin-right: 7px;"></i>
                    </div>
                    <h5 class="mb-0 ml-2 header-title d-flex align-items-center">My Address</h5>
                </a>
                @*<div id="information"></div>*@
            </div>
        </div>
    </div>
</header>
<div class="main-content app-main-area">
    <div class="Address-list p-3">
        <div class="row m-0">
            <div class="col-lg-12 col-12 p-0 mb-5">

                @for (int i = 0; i < ViewBag.AddressTypeData.TotalRecords; i++)
                {
                    <div class="card p-2 mb-2 br-15 is-loading" style="box-shadow: 0px 0px 14px 0px #00000024;">
                        <div class="row m-0">
                            <div class="col-lg-8 col-8 p-0 d-flex align-items-center">
                                <h5 class="mb-0">
                                    <i class="dripicons-home"></i>
                                    <span class="fs-15" style="margin-left:8px;">@ViewBag.AddressTypeData.Values[i].AddressTypeName</span>
                                    @if (@ViewBag.AddressTypeData.Values[i].IsDefault > 0)
                                    {
                                        <button type="button" style="padding: 0px 10px;" class="btn btn-soft-primary waves-effect waves-light btn btn-sm">Default</button>
                                    }
                                </h5>
                            </div>
                            <div class="col-lg-4 col-4 p-0">
                                <div style="float:right;">
                                    <a href="@Url.Action("Index","CreateAddress")?ri=@ViewBag.AddressTypeData.Values[i].Id" id="EditAddress" class="line-height-0">
                                        <button type="button" class="btn btn-soft-primary waves-effect waves-light" style="padding: 2px 5px; border-radius: 50px;"><i class="bx bx-edit-alt"></i></button>
                                    </a>
                                    <button type="button" onclick="ConfirmDeleteRecord(@ViewBag.AddressTypeData.Values[i].Id)" class="btn btn-soft-primary waves-effect waves-light" style="padding: 2px 5px; border-radius: 50px;"><i class="bx bx-trash-alt"></i></button>
                                </div>
                            </div>
                            <div class="col-lg-12 col-12 p-0">
                                <p class="mb-0 mt-1 fs-13">
                                    @ViewBag.AddressTypeData.Values[i].AddressLine1,
                                    @ViewBag.AddressTypeData.Values[i].PinCode
                                </p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="button-fixed">
            <a href="@Url.Action("Index","CreateAddress")" class="btn btn-primary w-md w-100 mt-2">
                <span>Add New Address</span>
            </a>
        </div>
    </div>
</div>

<script src="~/assets/libs/jquery/jquery.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>
<script>
    //Confirm Delete Record
    function ConfirmDeleteRecord(DataId) {
        Swal.fire({
            title: "Are you sure?",
            text: "", icon: "warning",
            confirmButtonColor: "#2ab57d",
            cancelButtonColor: "#fd625e",
            showCancelButton: !0,
            confirmButtonText: "Yes"
        }).then(
            function (result) {
                if (result.isConfirmed) {
                    DeleteAdminData(DataId);
                }
            }
        );
    }

     function DeleteAdminData(DataId) {
        $.ajax({
            url: '@Url.Action(Actions.DeletedAddressData, Controllers.CreateAddress, new { area = "" })',
            data: {
                AddressId: DataId
            },
            type: 'GET',
            datatype: 'json',
            success: function (response) {
                if (response.Code == 200) {
                    //Swal.fire({
                    //    position: 'center',
                    //    icon: 'success',
                    //    title: response.Message,
                    //    showConfirmButton: false,
                    //    timer: 2000
                    //})
                    setTimeout(function () {
                        window.location.reload();
                    }, 2000);
                }
            },
            error: function () { }
        });
    }
</script>