GinnyBuddyApp/Controllers/ChaiNastaController.cs
using AAH.Common.Paging;
using AAH.Services.Contract;
using GinnyBuddyApp.Infrastructure;
using System.Web.Mvc;
using GinnyBuddyApp.Pages;
using AAH.Common;
using AAH.Entities.V1;

namespace GinnyBuddyApp.Controllers
{
    public class ChaiNastaController : BaseController
    {
        public readonly AbstractItemsServices abstractItemsServices;
        public readonly AbstractVendorsServices abstractVendorsServices;
        public ChaiNastaController(AbstractItemsServices abstractItemsServices,
            AbstractVendorsServices abstractVendorsServices)
        {
            this.abstractItemsServices = abstractItemsServices;
            this.abstractVendorsServices = abstractVendorsServices;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult VendorProfile()
        {
            return View();
        }


        [HttpGet]
        [ActionName(Actions.GetAllItems)]
        public ActionResult GetAllItems(string Search = "")
        {
            PageParam pageParam = new PageParam();  
            pageParam.Offset = 0;
            pageParam.Limit = 10000;
            var result = abstractItemsServices.SearchItems_All(pageParam,Search, ProjectSession.AdminId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        [ActionName(Actions.ManageItems)]
        public ActionResult ManageItems(string Search = "")
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 10000;
            var result = abstractItemsServices.Items_All(pageParam, Search);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public JsonResult VendorProfileDetails(
        //    long Id = 0,
        //    string VendorName = "",
        //    string CabinName = "",
        //    string PrimaryPhoneNumber = "", 
        //    string AlternatePhoneNumber = "",
        //    string CameraPhoto = "",
        //    string Location = "",
        //    string CabinImage = "",
        //    string Items = "",
        //    string Timings = "",
        //    string Lat = "",
        //    string Long = ""
        //)
        //{
        //    Vendors vendors = new Vendors();
        //    vendors.Id = Id;
        //    vendors.VendorName = VendorName;
        //    vendors.CabinName = CabinName;
        //    vendors.PrimaryPhoneNumber = PrimaryPhoneNumber;
        //    vendors.AlternatePhoneNumber = AlternatePhoneNumber;
        //    vendors.CameraPhoto = CameraPhoto;
        //    vendors.Location = Location;
        //    vendors.CabinImage = CabinImage;
        //    vendors.Items = Items;
        //    vendors.Timings = Timings;
        //    vendors.Lat = Lat;
        //    vendors.Long = Long;
        //    vendors.CreatedBy = ProjectSession.AdminId;
        //    vendors.UpdatedBy = ProjectSession.AdminId;

        //    var result = abstractVendorsServices.Vendors_Upsert(vendors);
        //    return Json(result, JsonRequestBehavior.AllowGet);
        //}


    }
}

GinnyBuddyApp/Controllers/DashboardController.cs
using AAH.Common;
using AAH.Common.Paging;
using AAH.Services.Contract;
using GinnyBuddyApp.Infrastructure;
using System.Linq;
using System.Web.Mvc;

namespace GinnyBuddyApp.Controllers
{
    public class DashboardController : BaseController
    {
        public readonly AbstractOtherServiceIconsServices abstractOtherServiceIconsServices;
        public readonly AbstractRequestsServices abstractRequestsServices;
        public readonly AbstractAddressMasterServices abstractAddressMasterServices;
        public readonly AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices;
        public readonly AbstractMasterServicesServices abstractMasterServicesServices;
        public DashboardController(AbstractOtherServiceIconsServices abstractOtherServiceIconsServices,
            AbstractAddressMasterServices abstractAddressMasterServices,
             AbstractRequestsServices abstractRequestsServices,
             AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices,
             AbstractMasterServicesServices abstractMasterServicesServices)
        {
            this.abstractAddressMasterServices = abstractAddressMasterServices;
            this.abstractOtherServiceIconsServices = abstractOtherServiceIconsServices;
            this.abstractRequestsServices = abstractRequestsServices;
            this.abstractDeliveryExecutiveServices = abstractDeliveryExecutiveServices;
            this.abstractMasterServicesServices = abstractMasterServicesServices;
        }

        public ActionResult Index()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.RequestsData = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 20);
            ViewBag.MasterServicesData = abstractMasterServicesServices.MasterServices_All(pageParam, "");
            getDECountByAddress();
            return View();
        }
        [HttpPost]
        public JsonResult getDECountByAddress()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId).Values;
            if (result.Count > 0)
            {
                var ss = result.Where(x => x.IsDefault == 1).ToList();
                ViewBag.DCount = abstractDeliveryExecutiveServices.GetDeliveryExecutiveCountByAddressId(ss[0].Id.ToString());
            }
            else
            {
                ViewBag.DCount = null;
            }

            return Json(ViewBag.DCount, JsonRequestBehavior.AllowGet);
        }

        public JsonResult OtherServiceIconsData()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractOtherServiceIconsServices.OtherServiceIcons_All(pageParam,"");
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeliveryExecutiveServices()
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            var result = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 20);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

GinnyBuddyApp/Views/ChaiNasta/Index.cshtml
@using AAH.Common;
@using GinnyBuddyApp.Pages;
@using System.Web.Optimization;
@using GinnyBuddyApp.Infrastructure;

@Html.AntiForgeryToken()

@{
    ViewBag.Title = "Manage Chai Nasta Dish";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/assets/libs/dropzone/min/dropzone.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />


<div class="main-content app-main-area" id="hideMainArea">
    <div id="header_logo">
        <header id="page-topbar">
            <div class="navbar-header app-header-area p-0">
                <div class="row m-0 w-100 align-items-center">
                    <div class="col-lg-9 col-9 d-flex align-items-center">
                        <i class="bx bx-map fs-20"></i>
                        <div class="selected-address w-100" id="selectedAddress" style="line-height: 1.1 !important;">
                            <h6 class="mb-0"></h6>
                            <span></span>
                        </div>
                        <!-- <h5 class="mb-0 ml-2 header-title">Choose Address</h5> -->
                    </div>

                    <div class="col-lg-3 col-3">
                        <div class="d-flex align-items-center line-height-0 justify-content-center">
                            <a href="@Url.Action("Index","Dashboard")" class="text-dark btn btn-primary" style="
                        padding: 5px 5px;
                        color: #fff !important;
                        display: flex;
                    ">
                                <i class="bx bx-chevrons-left fs-20"></i>
                            </a>

                            <div class="line-height-0 ml-2" id="infoCircle" style="margin-left:6px;">
                                <a href="https://ginnybuddy.in/" class="text-dark">
                                    <i class="bx bx-info-circle fs-20"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <div class="logo pt-3 text-center">
            <img src="~/assets/ChaiNastaLogo.jpeg" width="120" alt="Alternate Text" />
        </div>
    </div>

    <div class="request-for">
        <div class="p-3" id="searchtop_bar">
            <div class="search-bar">
                <div class="d-flex align-items-center">
                    <i class="dripicons-chevron-left searchback-arrow" id="search_backarrow" onclick="backSearchaction()" style="width:30px;display:none;"></i>
                    <input onclick="actionSearch();" type="search" id="itemSearch" placeholder="Restaurant name or a dish..." name="itemSearch" class="form-control searchbar-input" value="" />
                    <i class="bx bx-search-alt searchback-arrow search-button" id="searching_box" onclick="SearchItemData()" style="display:none;"></i>
                </div>
            </div>
            
        </div>
        <div class="p-3 pt-0">
           
            @*Comming Soon*@
            <div class="w-100 text-center" id="comming_soon">
                <a href="@Url.Action("VendorProfile","ChaiNasta")">Vendor Profile</a>
                <p>Comming Soon</p>
            </div>

            @*Search time items area*@
            <div class="items-area" id="itemsbar_area" style="display:none;">
                <div class="items-menubar mt-3">
                    <div class="row m-0" id="itemsListing">

                    </div>
                    <div id="itemsNotfound">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br />
<br />
<br />

@*Bottom Bar Render*@
@RenderPage("~/Views/BottomBar/Index.cshtml")

<script src="~/assets/libs/jquery/jquery.min.js"></script>
<script>

    $(document).ready(function () {
        ItemsList();
    })

    function actionSearch() {
        $("#header_logo").hide();
        $("#searchtop_bar").addClass("bg-white , search-fix")
        $("#hideMainArea").css("margin-top","75px")
        $("#comming_soon").hide();
        $("#itemsbar_area").show();
        $("#searching_box").show();
        $("#search_backarrow").show();
    }

    function backSearchaction() {
        $("#header_logo").show();
        $("#searchtop_bar").removeClass("bg-white , search-fix")
        $("#hideMainArea").css("margin-top", "50px")
        $("#comming_soon").show();
        $("#itemsbar_area").hide();
        $("#searching_box").hide();
        $("#search_backarrow").hide();
        $("#itemSearch").val("");
        $("#itemsNotfound").html("");
        $("#itemsListing").html("");
    }

    function SearchItemData() {
        $("#itemsListing").html("");
        $("#itemsNotfound").html("");
        var itemSearchdata = $("#itemSearch").val();

        $.ajax({
            type: "get",
            url: '@Url.Action(Actions.GetAllItems, Controllers.ChaiNasta)',
            data: { Search: itemSearchdata },
            dataType: 'json',
            success: function (response) {
                if (response.Values.length > 0) {
                    for (var i = 0; i < response.Values.length; i++) {
                        $("#itemsListing")
                            .append(`<div class="col-lg-12 p-0 d-flex align-items-center mb-2">

                                    ${response.Values[i].ImageUrl == "" || response.Values[i].ImageUrl == null ?
                                    `<div class="items-image">
                                        <img src="../assets/not-found.png"
                                             alt="Item" />
                                    </div>` :
                                    `<div class="items-image">
                                        <img src="http://localhost:60609/${response.Values[i].ImageUrl}"
                                             alt="Item" />
                                    </div>`}

                                    <div class="item-description">
                                        <p class="mb-0">${response.Values[i].Name}</p>
                                        <span>Dish</span>
                                    </div>
                                </div>`)
                    }
                } else {

                    $("#itemsNotfound").append(`<p class="text-center">
                            <span style="font-weight:600;">Uh-oh!</span> <br />
                            No resultd for <span style="color:#000;">${itemSearchdata}</span> in Delivery. Please try
                            something else.
                        </p>`)
                }
            },
            error: function (error) {
                console.log('error', error);
            }
        })
    }

</script>