GinnyBuddyResponderApp/Controllers/AuthenticationController.cs
using AAH.Common;
using AAH.Services.Contract;
using System;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.IO;
using System.Configuration;

namespace GinnyBuddyResponderApp.Controllers
{
    public class AuthenticationController : Controller
    {
        public readonly AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices;
        public AuthenticationController(AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices)
        {
            this.abstractDeliveryExecutiveServices = abstractDeliveryExecutiveServices;
        }
        
        public ActionResult SignIn(string DeviceToken  = "")
        {
            ViewBag.DeviceTokenStr = DeviceToken;
            return View();
        }
        public JsonResult SendOtp(string MobileNumber = "" , string DeviceToken = "")
        {
            string otp = Convert.ToString(new Random().Next(111111, 999999).ToString("D6"));
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(HttpUtility.UrlDecode(ConfigurationManager.AppSettings["smsapi"]).
                Replace("#mobile#", MobileNumber.ToString()).Replace("#otp#", otp).ToString());
            request.Method = "GET";
            request.ContentType = "application/json";

            if (MobileNumber == "1234512345")
            {
                otp = "123456";
            }

            var result = abstractDeliveryExecutiveServices.DeliveryExecutive_SendOTP(MobileNumber, DeviceToken, "NO","NO","NO", Convert.ToInt64(otp));

            if (result.Code == 200)
            {
                try
                {
                    WebResponse webResponse = request.GetResponse();
                    using (Stream webStream = webResponse.GetResponseStream() ?? Stream.Null)
                    using (StreamReader responseReader = new StreamReader(webStream))
                    {
                        string response = responseReader.ReadToEnd();
                    }
                }
                catch (Exception e)
                {
                    Console.Out.WriteLine("-----------------");
                    Console.Out.WriteLine(e.Message);
                }

                    Session.Clear();
                    ProjectSession.AdminId = result.Item.Id;
                    HttpCookie cookie = new HttpCookie("SendOTP");
                    cookie.Values.Add("Id", result.Item.Id.ToString());
                    cookie.Expires = DateTime.Now.AddYears(100);
                    Response.Cookies.Add(cookie);
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult VerifyOtp(long Otp = 0,string DeviceToken = "")
        {
            var Id = "0";
            HttpCookie reqCookies = Request.Cookies["SendOTP"];
            if (reqCookies != null)
            {
                Id = reqCookies["Id"].ToString();
            }

            var result = abstractDeliveryExecutiveServices.DeliveryExecutive_VerifyOtp(Convert.ToInt64(Id), DeviceToken, Otp, "NO", "NO", "NO");

            if(result.Code == 200)
            {
                Session.Clear();
                HttpCookie cookie = new HttpCookie("AdminLogin");
                cookie.Values.Add("Id", result.Item.Id.ToString());
                cookie.Values.Add("AdminName", result.Item.FirstName.ToString() + " " + result.Item.LastName.ToString());
                cookie.Values.Add("ProfileURL", result.Item.ProfileURLStr.ToString());
                cookie.Values.Add("MobileNumber", result.Item.MobileNumber.ToString());
                cookie.Values.Add("IsAvailable", result.Item.IsAvailable.ToString());
                cookie.Values.Add("AreaName", result.Item.MasterAreaName.ToString());
                cookie.Values.Add("IsMarketingPerson", result.Item.IsMarketingPerson.ToString());

                cookie.Expires = DateTime.Now.AddYears(100);
                Response.Cookies.Add(cookie);

                ProjectSession.AdminId = result.Item.Id;
                ProjectSession.AdminName = result.Item.FirstName + " " + result.Item.LastName;
                ProjectSession.ProfileURL = result.Item.ProfileURLStr;
                ProjectSession.MobileNumber = result.Item.MobileNumber;
                ProjectSession.IsAvailable = result.Item.IsAvailable;
                ProjectSession.AreaName = result.Item.MasterAreaName;
                ProjectSession.IsMarketingPerson = result.Item.IsMarketingPerson;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();
            Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetNoStore();
            if (Request.Cookies["AdminLogin"] != null)
            {
                var c = new HttpCookie("AdminLogin");
                c.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(c);
            }

            if (Request.Cookies["SendOTP"] != null)
            {
                var c = new HttpCookie("SendOTP");
                c.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(c);
            }

            return Json("", JsonRequestBehavior.AllowGet);

        }

    }
}

GinnyBuddyResponderApp/Controllers/DashboardController.cs
using AAH.Common;
using AAH.Common.Paging;
using AAH.Services.Contract;
using GinnyBuddyResponderApp.Infrastructure;
using System.Web;
using System.Web.Mvc;
using GinnyBuddyResponderApp.Pages;
using System.Data.SqlClient;
using System.Data;
using System.Text;

namespace GinnyBuddyResponderApp.Controllers
{
    public class DashboardController : BaseController
    {
        public readonly AbstractOtherServiceIconsServices abstractOtherServiceIconsServices;
        public readonly AbstractRequestsServices abstractRequestsServices;
        public readonly AbstractAddressMasterServices abstractAddressMasterServices;
        public readonly AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices;
        public DashboardController(AbstractOtherServiceIconsServices abstractOtherServiceIconsServices,
            AbstractAddressMasterServices abstractAddressMasterServices,
             AbstractRequestsServices abstractRequestsServices,
             AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices)
        {
            this.abstractAddressMasterServices = abstractAddressMasterServices;
            this.abstractOtherServiceIconsServices = abstractOtherServiceIconsServices;
            this.abstractRequestsServices = abstractRequestsServices;
            this.abstractDeliveryExecutiveServices = abstractDeliveryExecutiveServices;
        }

        public ActionResult Index(long id = 0)
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.RequestsData = abstractRequestsServices.GetRequestByDeliveryExecutiveId(pageParam, "", ProjectSession.AdminId, 3);
            ViewBag.DeliveryExecutiveIdData = abstractDeliveryExecutiveServices.DeliveryExecutive_ById(ProjectSession.AdminId).Item;
            var Id = "0";
            HttpCookie reqCookies = Request.Cookies["AdminLogin"];
            if (reqCookies != null)
            {
                Id = reqCookies["Id"].ToString();
            }
            if (id == 0)
            {
                return RedirectToAction(Actions.Index, Pages.Controllers.Dashboard, new { Area = "", id = Id });
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public JsonResult Dashboard_ById()
        {
            long Id = ProjectSession.AdminId;
            var result = abstractDeliveryExecutiveServices.Dashboard_ById(Id);

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

GinnyBuddyResponderApp/Controllers/ProfilesController.cs
using AAH.Common;
using AAH.Common.Paging;
using AAH.Entities.Contract;
using AAH.Services.Contract;
using GinnyBuddyResponderApp.Infrastructure;
using System;
using System.Web.Mvc;
using GinnyBuddyResponderApp.Pages;
using AAH.Entities.V1;
using static GinnyBuddyResponderApp.Infrastructure.Enums;
using System.IO;
using System.Web;

namespace GinnyBuddyResponderApp.Controllers
{
    public class ProfilesController : BaseController
    {
        public readonly AbstractAddressMasterServices abstractAddressMasterServices;
        public readonly AbstractRequestsServices abstractRequestsServices;
        public readonly AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices;
        public ProfilesController(AbstractAddressMasterServices abstractAddressMasterServices,
            AbstractRequestsServices abstractRequestsServices,
            AbstractDeliveryExecutiveServices abstractDeliveryExecutiveServices)
        {
            this.abstractAddressMasterServices = abstractAddressMasterServices;
            this.abstractRequestsServices = abstractRequestsServices;
            this.abstractDeliveryExecutiveServices = abstractDeliveryExecutiveServices;
        }

        public ActionResult Index()
        {   
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000;
            ViewBag.DeliveryExecutiveIdData = abstractDeliveryExecutiveServices.DeliveryExecutive_ById(ProjectSession.AdminId).Item;
            ViewBag.AddressTypeData = abstractAddressMasterServices.AddressMaster_ByUserId(pageParam, "", ProjectSession.AdminId);
            ViewBag.RequestsData = abstractRequestsServices.Requests_All(pageParam, "", ProjectSession.AdminId, 0, 0, 0, 0);
            ViewBag.UserData = abstractDeliveryExecutiveServices.DeliveryExecutive_ById(ProjectSession.AdminId).Item;
            return View();
        }

        public ActionResult EditProfile()
        {
            AbstractDeliveryExecutive abstractDeliveryExecutive = abstractDeliveryExecutiveServices.DeliveryExecutive_ById(ProjectSession.AdminId).Item;
            ViewBag.DeliveryExecutiveIdData = abstractDeliveryExecutiveServices.DeliveryExecutive_ById(ProjectSession.AdminId).Item;
            return View(abstractDeliveryExecutive);
        }

        //Create Admin Data

        [HttpPost]
        [ValidateInput(false)]
        [ActionName(Actions.UpsertDeliveryExecutiveDetails)]
        public ActionResult UpsertDeliveryExecutiveDetails(DeliveryExecutive deliveryExecutive)
        {
            try
            {
                if(deliveryExecutive.Id == 0)
                {
                    deliveryExecutive.CreatedBy = ProjectSession.AdminId;
                } else
                {
                    deliveryExecutive.UpdatedBy = ProjectSession.AdminId;
                }

                if (deliveryExecutive.Files != null)
                {
                    string basePath = "DeliveryExecutiveProfile/" + deliveryExecutive.Id + "/";
                    string fileName = DateTime.Now.ToString("ddMMyyyyhhmmss") + "_" + Path.GetFileName(deliveryExecutive.Files.FileName);
                    string path = Server.MapPath("~/" + basePath);
                    if (!Directory.Exists(Path.Combine(HttpContext.Server.MapPath("~/" + basePath))))
                    {
                        Directory.CreateDirectory(HttpContext.Server.MapPath("~/" + basePath));
                    }
                    deliveryExecutive.Files.SaveAs(HttpContext.Server.MapPath("~/" + basePath + fileName));
                    deliveryExecutive.ProfileURL = basePath + fileName;
                }

                SuccessResult<AbstractDeliveryExecutive> result = new SuccessResult<AbstractDeliveryExecutive>();
                result = abstractDeliveryExecutiveServices.DeliveryExecutive_Upsert(deliveryExecutive);

                Session.Clear();
                HttpCookie cookie = new HttpCookie("AdminLogin");
                cookie.Values.Add("Id", result.Item.Id.ToString());
                cookie.Values.Add("AdminName", result.Item.FirstName.ToString() + " " + result.Item.LastName.ToString());
                cookie.Values.Add("MobileNumber", result.Item.MobileNumber.ToString());
                cookie.Values.Add("ProfileURL", result.Item.ProfileURLStr.ToString());
                cookie.Values.Add("IsAvailable", result.Item.IsAvailable.ToString());
                cookie.Expires = DateTime.Now.AddYears(100);
                Response.Cookies.Add(cookie);

                ProjectSession.AdminId = result.Item.Id;
                ProjectSession.AdminName = result.Item.FirstName + " " + result.Item.LastName;
                ProjectSession.MobileNumber = result.Item.MobileNumber;
                ProjectSession.ProfileURL = result.Item.ProfileURLStr;
                ProjectSession.IsAvailable = result.Item.IsAvailable;

                if (result != null && result.Code == 200 && result.Item != null)
                {
                    return RedirectToAction(Actions.Index, Pages.Controllers.Dashboard, new { Area = "", id = result.Item.Id });
                }
                else
                {
                    TempData["openPopup"] = CommonHelper.ShowAlertMessageToastr(MessageType.danger.ToString(), result.Message);
                }
            }
            catch (Exception error)
            {
                TempData["openPopup"] = CommonHelper.ShowAlertMessageToastr(MessageType.danger.ToString(), error);
            }

            return RedirectToAction(Actions.EditProfile, Pages.Controllers.Profiles, new { Area = "" });
        }
    }
}

GinnyBuddyResponderApp/Views/Profiles/EditProfile.cshtml
@using AAH.Common;
@using GinnyBuddyResponderApp.Pages;
@using System.Web.Optimization;
@using GinnyBuddyResponderApp.Infrastructure;
@using AAH.Entities.V1;
@model DeliveryExecutive

@Html.AntiForgeryToken()

@{
    ViewBag.Title = "Edit Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #map-canvas {
        height: 225px;
        width: 100%;
        margin-bottom: 80px;
    }
</style>

<div class="main-content app-main-area">
    <div class="request-for p-3">
        @using (Html.BeginForm(Actions.UpsertDeliveryExecutiveDetails, Controllers.Profiles, new { Area = "" }, FormMethod.Post, new { id = "usesDetails", @class = "", @enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Latitude)
            @Html.HiddenFor(model => model.Longitude)
            @Html.HiddenFor(model => model.Pincode)

            <div class="row m-0 mb-2">
                <div class="col-xl-12 col-12 p-0">
                    <div class="form-group mb-2">
                        <label class="mb-1">Profile Image</label><br>
                        @if (Model.ProfileURL != null && Model.ProfileURL != "")
                        {
                            <img src="@Model.ProfileURLStr" class="round-img-profile">
                        }
                        @Html.TextBoxFor(model => model.Files, new { @Type = "file", @class = "form-control mt-2" })
                    </div>
                </div>
                <div class="col-xl-12 col-12 p-0">
                    <div class="form-group mb-2">
                        <label class="mb-1">First Name</label>
                        @Html.TextBoxFor(model => model.FirstName, new { @Type = "text", @class = "form-control", @placeholder = "Enter First Name" })
                    </div>
                </div>
                <div class="col-xl-12 col-12 p-0">
                    <div class="form-group mb-2">
                        <label class="mb-1">Last Name</label>
                        @Html.TextBoxFor(model => model.LastName, new { @Type = "text", @class = "form-control", @placeholder = "Enter Last Name" })
                    </div>
                </div>
                <div class="col-xl-12 col-12 p-0">
                    <div class="form-group mb-2">
                        <label class="mb-1">Phone Number</label>
                        @Html.TextBoxFor(model => model.MobileNumber, new { @Type = "number", @readonly = "readonly", @class = "form-control", @placeholder = "Enter Phone Number" })
                    </div>
                </div>
                <div class="col-xl-12 col-12 p-0">
                    <div class="form-group mb-2">
                        <label class="mb-1">Address</label>
                        @Html.TextBoxFor(model => model.AddressLine1, new { @Type = "text", @class = "form-control", @placeholder = "Select Address" })
                    </div>
                </div>
            </div>
                
            <div id="map-canvas"></div>
            
            <div class="button-fixed">
                <button type="submit" class="btn btn-primary w-md w-100 mt-2">
                    <span>Update Profile</span>
                </button>
            </div>
        }
    </div>
</div>

<script src="~/assets/libs/jquery/jquery.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>

@*Google map*@ 
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB97EhOhMCYhK1tZIofUkpKcGW61fdgKjg&libraries=places&callback=initMap" async defer></script>
<script language=javascript src='http://maps.google.com/maps/api/js?sensor=false'></script>

<script>

    $(document).ready(function () {
        if ($("#Id").val() > 0) {
            setTimeout(function () {
                pinOnMap();
            }, 1500)
        }
    });

    function initMap() {
        getCurrentLatLong()
    }

    $("#usesDetails").validate({
        rules: {
            FirstName: {
                required: true
            },
            LastName: {
                required: true
            },
            AddressLine1: {
                required: true
            },
        },
        messages: {
            FirstName: {
                required: "Please enter your first name",
            },
            LastName: {
                required: "Please enter your last name",
            },
            AddressLine1: {
                required: "Please select your address",
            },
        },
        errorPlacement: function (error, element) {
            if (element.is(":radio")) {
                error.appendTo(element.parents('.form-group'));
            }
            else {
                error.insertAfter(element);
            }
        },
        submitHandler: function (form) {
            form.submit();
        }
    });

    $('#AddressLine1').on('input', function () {
        placeMAPAddress();
    });

    function getCurrentLatLong(CurrentLat, CurrentLong) {
        if (document.getElementById('map-canvas')) {

            if ("geolocation" in navigator) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    CurrentLat = position.coords.latitude;
                    CurrentLong = position.coords.longitude;
                });
            } else {
                console.log("Browser doesn't support geolocation!");
            }

            var content;
            var latitude = CurrentLat;
            var longitude = CurrentLong;
            var map;
            var marker;
            navigator.geolocation.getCurrentPosition(loadMap);

            function demo() {
                google.maps.event.addListener(map, 'click', function (e) {
                    placeMarker(e.latLng);
                });
            }

            function loadMap(location) {
                if (location.coords) {
                    latitude = location.coords.latitude;
                    longitude = location.coords.longitude;
                }

                var myLatlng = new google.maps.LatLng(latitude, longitude);

                var mapOptions = {
                    zoom: 14,
                    center: myLatlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };

                map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

                content = document.getElementById('information');

                demo();

                var input = document.getElementById('search_input');
                map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

                var searchBox = new google.maps.places.SearchBox(input);

                google.maps.event.addListener(searchBox, 'places_changed', function () {
                    var places = searchBox.getPlaces();
                });

                marker = new google.maps.Marker({
                    map: map
                });
            }
        }

        function placeMarker(location) {
            marker.setPosition(location);
            $.ajax({
                type: "POST",
                url: `https://maps.googleapis.com/maps/api/geocode/json?latlng=${location.lat()},${location.lng()}&key=AIzaSyABofRnRkpT_4m344ZOsyRnT90uSGF5H6A`,
                dataType: 'json',
                success: function (response) {
                    if (response != null) {
                        $("#AddressLat").val(location.lat());
                        $("#AddressLong").val(location.lng());

                        $("#addressLine").text(response.results[0].formatted_address);
                        $("#AddressPincode").val(response.results[0].address_components[5].long_name);

                        for (var i = 0; i < response.results[0].address_components.length; i++) {
                            if (response.results[0].address_components[i].types[0] == "postal_code") {
                                $("#AddressPincode").val(response.results[0].address_components[i].long_name);
                            }
                        }

                    }
                    console.log('response', response);
                },
                error: function (error) {
                }
            });
        }
    }

    function placeMAPAddress() {
        var input = document.getElementById('AddressLine1');
        var originLatitude = document.getElementById('Latitude');
        var originLongitude = document.getElementById('Longitude');
        var AddressPincode = document.getElementById('Pincode');

        var originAutocomplete = new google.maps.places.Autocomplete(input);


        originAutocomplete.addListener('place_changed', function (event) {
            var place = originAutocomplete.getPlace();

            if (place.hasOwnProperty('place_id')) {
                if (!place.geometry) {
                    return;
                }
                originLatitude.value = place.geometry.location.lat();
                originLongitude.value = place.geometry.location.lng();
                AddressPincode.value = place.address_components.slice(-1)[0].long_name;

                pinOnMap();
            } else {
                service.textSearch({
                    query: place.name
                }, function (results, status) {
                    if (status == google.maps.places.PlacesServiceStatus.OK) {
                        originLatitude.value = results[0].geometry.location.lat();
                        originLongitude.value = results[0].geometry.location.lng();
                        AddressPincode.value = place.address_components.slice(-1)[0].long_name;
                        pinOnMap();
                    }
                });
            }
        });
    }

    function pinOnMap() {
        var map = new google.maps.Map(document.getElementById('map-canvas'), {
            zoom: 15,
            center: new google.maps.LatLng($("#Latitude").val(), $("#Longitude").val()),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });
        var infowindow = new google.maps.InfoWindow();
        var marker, i;
        marker = new google.maps.Marker({
            position: new google.maps.LatLng($("#Latitude").val(), $("#Longitude").val()),
            map: map
        });
        google.maps.event.addListener(marker, 'click', (function (marker, i) {
            return function () {
                infowindow.open(map, marker);
            }
        })(marker, i));
    }

</script>

GinnyBuddyResponderApp/Views/Profiles/Index.cshtml
@using AAH.Common;
@using GinnyBuddyResponderApp.Pages;
@using System.Web.Optimization;
@using GinnyBuddyResponderApp.Infrastructure;

@Html.AntiForgeryToken()

@{
    ViewBag.Title = "Create Request";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .icon-box {
        width: 45px;
        height: 45px;
        line-height: 40px;
        text-align: center;
        background: rgba(115,103,240,.12);
        border-radius: 50%;
        color: #7367f0;
        display: flex;
        align-items: center;
    }
</style>
<header id="page-topbar">
    <div class="navbar-header app-header-area p-0">
        <div class="row m-0 w-100">
            <div class="col-lg-8 col-8 d-flex align-items-center">
                <a href="@Url.Action("Index","Dashboard")">
                    <h5 class="mb-0 ml-2 header-title d-flex align-items-center"><i class="dripicons-arrow-thin-left fs-20 d-flex" style="margin-right: 7px;"></i>Profile</h5>
                </a>
            </div>
            <div class="col-lg-4 col-4">
                <div style="float:right;">
                    <a href="@Url.Action("EditProfile","Profiles")">
                        <i class="bx bx-edit-alt text-dark align-middle fs-20"></i>
                        @*<div type="button" class="btn btn-soft-primary waves-effect waves-light" style="padding: 2px 5px; border-radius: 50px;"><i class="bx bx-edit-alt"></i></div>*@
                    </a>
                    @*<a href="javascript:void(0)" onclick="ConfirmLogOutModal();" style="margin-left:10px;">
                        <i class="mdi mdi-logout text-dark align-middle me-1 fs-20"></i>
                    </a>*@
                </div>
            </div>
        </div>
    </div>
</header>
<div class="main-content app-main-area">
    <div class="request-for p-3">
        <div class="card p-3 mb-1 text-center common-bx-shadow">
            <h4 class="mb-2 fs-16">@ViewBag.UserData.FirstName @ViewBag.UserData.LastName</h4>
            <p class="mb-0 fs-12">@ViewBag.UserData.MobileNumber</p>
        </div>
        <div class="row m-0">
            <div class="col-lg-6 col-6 p-1" style="padding-left:0px !important;">
                <a href="@Url.Action("ManageAddress","CreateAddress")">
                    <div class="card p-2 list-box common-bx-shadow">
                        <div class="d-flex align-items-center">
                            <i class="dripicons-location icon-box fs-20 d-flex justify-content-center"></i>
                            <div class="text-left" style="line-height:1;margin-left:5px;">
                                <h5 class="mb-0">@ViewBag.AddressTypeData.TotalRecords</h5>
                                <p class="mb-0 fs-12">My Address</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-6 col-6 p-1" style="padding-right:0px !important;">
                <a href="@Url.Action("ManageRequest","CreateRequest")">
                    <div class="card p-2 list-box common-bx-shadow">
                        <div class="d-flex align-items-center">
                            <i class="dripicons-device-mobile icon-box fs-20 d-flex justify-content-center"></i>
                            <div class="text-left" style="line-height:1;margin-left:5px;">
                                <h5 class="mb-0">@ViewBag.RequestsData.TotalRecords</h5>
                                <p class="mb-0 fs-12">My Requests</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-6 col-6 p-1" style="padding-right:0px !important;">
                <a href="@Url.Action("Feedback","CreateRequest")">
                    <div class="card p-2 list-box common-bx-shadow">
                        <div class="d-flex align-items-center">
                            <i class="dripicons-blog icon-box fs-20 d-flex justify-content-center"></i>
                            <div class="text-left" style="line-height:1;margin-left:5px;">
                                <h5 class="mb-0">@ViewBag.FeedbackData.TotalRecords</h5>
                                <p class="mb-0 fs-12">My Feedback</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

@*Confirmation alert*@
<div class="modal fade" id="confirmLogout" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="address-select text-center" id="ChooseAdddressMaster">

                    <h5>LogOut</h5>
                    <p class="fs-12">
                        Are you sure you want to Logout?
                    </p>
                    <div>
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">No</button>
                        <a href="@Url.Action("LogOut","Authentication")" class="btn btn-primary">Yes</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/assets/libs/jquery/jquery.min.js"></script>
<script src="~/assets/js/VoiceRecord.js"></script>
<script>
    function ConfirmLogOutModal() {
        $("#confirmLogout").modal('show');
    }

</script>
@Html.Raw(ViewBag.openPopup)